// vMMU domain models: Spaces, Pages, PageTables
//
// - Spaces: physical namespaces that can be mounted/exported
// - Pages: immutable chunks of territory (content stored in DB)
// - PageEntry: per-session attention (heat + accessed_at)

use chrono::Utc;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A physical partition / namespace that can be mounted by an agent.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Space {
    pub id: Uuid,
    pub name: String,
    /// i64 unix timestamp (seconds)
    pub created_at: i64,
}

impl Space {
    /// Construct with an explicit id.
    pub fn new_with_id(id: Uuid, name: impl Into<String>) -> Self {
        Self {
            id,
            name: name.into(),
            created_at: Utc::now().timestamp(),
        }
    }

    /// Construct with a freshly-generated UUID (v4 by default).
    /// Consumers that require v7 should pass an explicit `Uuid` generated by the caller.
    pub fn new(name: impl Into<String>) -> Self {
        Self::new_with_id(Uuid::new_v4(), name)
    }
}

/// Immutable chunk of context stored in a `Space`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Page {
    pub id: Uuid,
    pub space_id: Uuid,
    pub content: String,
    /// i64 unix timestamp (seconds)
    pub created_at: i64,
}

impl Page {
    pub fn new_with_id(id: Uuid, space_id: Uuid, content: impl Into<String>) -> Self {
        Self {
            id,
            space_id,
            content: content.into(),
            created_at: Utc::now().timestamp(),
        }
    }

    /// Create a Page with an auto-generated id (UUID v4).
    pub fn new(space_id: Uuid, content: impl Into<String>) -> Self {
        Self::new_with_id(Uuid::new_v4(), space_id, content)
    }
}

/// Session-scoped attention record for a Page (the `PageTable` entry).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PageEntry {
    pub session_id: Uuid,
    pub page_id: Uuid,
    /// 0.0 ..= 1.0
    pub heat: f32,
    /// i64 unix timestamp (seconds)
    pub accessed_at: i64,
}

impl PageEntry {
    /// New entry starts hot (1.0) and records `accessed_at`.
    pub fn new(session_id: Uuid, page_id: Uuid) -> Self {
        Self {
            session_id,
            page_id,
            heat: 1.0f32,
            accessed_at: Utc::now().timestamp(),
        }
    }

    /// Bump heat (clamped 0.0..=1.0) and refresh access time.
    pub fn bump(&mut self, delta: f32) {
        let new_heat = (self.heat + delta).clamp(0.0, 1.0);
        self.heat = new_heat;
        self.accessed_at = Utc::now().timestamp();
    }

    /// Touch without changing heat (updates accessed_at)
    pub fn touch(&mut self) {
        self.accessed_at = Utc::now().timestamp();
    }
}
