-- 0024_prune_batch_edges_v2.sql
-- Corrected cleanup: delete ALL temporal_proximity edges with weight=0.5.
-- These were generated by the old constant-weight 1h-window algorithm.
-- The new algorithm uses exp(-dt/300) weighting, so weight=0.5 edges
-- are exclusively from the old algo and safe to purge.

DELETE FROM golden_edges
WHERE edge_type = 'temporal_proximity'
  AND weight = 0.5;
